[project]
name = "kata-ai-meeting-assistant-clever-foxes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.2.0",
    "pytest>=8.4.2",
    "python-dotenv>=1.1.1",
]
